version: '3'
services:
    web:
        restart: always
        build: .
        ports:
            - "80:80"
        volumes:
            - .:/code
        working_dir: /code
        command: ./manage.py runserver 0.0.0.0:80
        environment:
            - PYTHONUNBUFFERED=0
